# Generated by Django 5.1.6 on 2025-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
