# Generated by Django 5.1.6 on 2025-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
